function Checkout() {
    // NEED: DISPLAY CART ON PAGE IN TABLE FORMAT. JUST NAME AND COST OF EACH PIZZA
    // NEED: DISPLAY USER INFO AS PER README
    // NEED: CHECKOUT BUTTON
        // ON-CLICK: SEND USER INFO, ORDER TOTAL, AND ARRAY OF PIZZAS TO SERVER
            // SHOW CONFIRMATION DIALOG -- SWEETALERT TIME!
            // NAVIGATE USER BACK TO SELECT PIZZA PAGE
            // CLLEAR REDUCERS AS APPROPRIATE
    return (
        <>
        </>
    )
}
export default Checkout;